[package]
name = "sky_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = "1.13.2"
lazy_static = "1.4.0"
minifb = "0.28.0"
rand = "0.8"

[dev-dependencies]
criterion = "0.4"
cgmath = "0.18"
hecs = "0.10.5"
bevy_ecs = "0.18.1"

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "iter"
harness = false

[[bench]]
name = "entity"
harness = false

[[bench]]
name = "sky"
harness = false

[[bench]]
name = "hevy"
harness = false

[profile.release]
debug = true
