[package]
name = "sky_ecs"
version = "0.1.0"
edition = "2021"
description = "Chunk-based ECS core for Sky"
readme = "README.md"
license = "MIT"
repository = "https://github.com/jz315/SkyEngine"
homepage = "https://github.com/jz315/SkyEngine"
documentation = "https://docs.rs/sky_ecs"

[dependencies]
lazy_static = "1.4.0"
rayon = "1.10"
rustc-hash = "2.1.2"
sky_type = { version = "0.1.0", path = "../sky_type" }
sky_profile = { version = "0.1.0", path = "../sky_profile", optional = true }
smallvec = "1.13.2"
sky_ecs_derive = { version = "0.1.0", path = "../sky_ecs_derive" }

[features]
default = []
profile = ["dep:sky_profile"]
