[package]
name = "sky_ecs_derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for Sky ECS typed queries"
license = "MIT"
repository = "https://github.com/jz315/SkyEngine"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
