[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = ".cargo/lld-link-wrapper.cmd"

[alias]
compare-ecs = ["bench", "--manifest-path", "tools/ecs-comparison/Cargo.toml", "--bench", "fair"]
